### ISSUE TITLE
changeUiStatus和changeUiStatusIgnore有什么区别

### ISSUE THREAD

**Issue by 13938417646** [FengChenSunshine/UiStatus#1]
如题

**Comment by FengChenSunshine** [comment]
changeUiStatusIgnore方法切换视图状态时，
如果当前显示的视图是UiStatus.CONTENT内容视图则会忽略该次切换视图请求；
而使用changeUiStatus方法时不会忽略。
这很实用，比如你将该库集成封装到网络请求框架里时，
第一次加载页面成功显示为内容视图，当再次调用api接口刷新页面失败(比如网络未连接)时，
如果使用的是changeUiStatusIgnore方法这时就不会将内容视图切换为网络错误视图，
这时你应该Toast提示，对用户而言这样交互会友好一点。
除非你需求是必须执行切换动作时要使用changeUiStatus，
否则应该尽可能的使用changeUiStatusIgnore进行切换视图动作。

**Comment by 13938417646** [comment]
ok,谢谢。还有个问题就是怎么控制每个页面的内容视图为指定的某部分视图呢？

**Comment by FengChenSunshine** [comment]
控制每个页面的内容视图为指定的某部分视图呢？

这个没有理解，你指的是？

是怎样控制页面显示指定状态的视图吗？

**Comment by 13938417646** [comment]
我的意思是UiStatus.CONTENT内容视图现在是整个activity的view，怎么控制这个CONTENT为activity中的某一部分view

**Comment by FengChenSunshine** [comment]
这个文档中有说明：
如果你需要控制的对象是view，就不能使用UiStatusController.get().bind(activity);构建UiStatusController对象。
使用UiStatusController.get().bind(view);构建UiStatusController对象，
参数view传递你需要使用状态控制的view即可。

**Comment by 13938417646** [comment]
好的，明白了。谢谢，没其他问题了，之后使用若有遇到其他问题在提出来。  这个库很不错，赞

**Comment by FengChenSunshine** [comment]
谢谢(*^▽^*)，其它几个库也不错的^_^，可以看看，O(∩_∩)O哈哈~ 互相学习 欢迎交流
