### ISSUE TITLE
使用kotlin anko写的布局,UiStatusController.get().bind(控件) 不显示loading状态，普通xml布局写的没问题。求教

### ISSUE THREAD

**Issue by BigBigDeBoy** [FengChenSunshine/UiStatus#3]

**Comment by FengChenSunshine** [comment]
override fun onCreate(savedInstanceState: Bundle?) {
               super.onCreate(savedInstanceState)

               frameLayout {
               relativeLayout {
                     button("按钮") {
                            textSize = sp(12).toFloat()
                           onClick {
                                  longToast("点击了按钮")
                           }
                    }.lparams {
                         centerInParent()
                   }
              }.lparams(matchParent, matchParent)
        }

        UiStatusManager.getInstance().addUiStatusConfig(UiStatus.LOADING, R.layout.ui_status_loading)
        var mUiStatusController = UiStatusController.get().bind(this)

        Handler().postDelayed({
            mUiStatusController.changeUiStatusIgnore(UiStatus.CONTENT)
        }, 1000)
    }

       我使用上面的代码测试是没有问题的，打开界面会先显示Loading状态视图，在1s后成功切换到了内容视图。
       您可以检查下您的代码，如果还是不能显示的话方便的话提供下你使用的代码示例。

**Comment by FengChenSunshine** [comment]
UIStatus内部设置的内容视图(UIStatus.CONTENT状态视图)的LayoutParams，如果使用bind(View view)时页面不显示，可以查看是否没有设置绑定控件的LayoutParams参数。

**Comment by FengChenSunshine** [comment]
UIStatus内部设置的内容视图(UIStatus.CONTENT状态视图)的LayoutParams，如果使用bind(View view)时页面不显示，可以查看是否没有设置绑定控件的LayoutParams参数。
