### ISSUE TITLE
加载框问题请教

### ISSUE THREAD

**Issue by AndroidKid19** [FengChenSunshine/UiStatus#4]
请问出现加载的时候怎么保持底部状态也不变。是否可以加个微信指导指导，微信：yww_y9

**Comment by FengChenSunshine** [comment]
可以加我微信DL781613203交流

**Comment by cqboy** [comment]
没看懂为啥一楼给了微信，二楼还会甩微信出来。

**Comment by FengChenSunshine** [comment]
在1.0.4以上版本修改原UiStatus.WIDGET_FLOAT状态名称为WIDGET_FLOOR；
并新增状态UiStatus.WIDGET_FLOAT，该状态提供一个可以浮动在内容视图上的视图状态.
通过这个小部件可以实现类似在CONTENT状态上展示LOADING视图效果来代替UiStatus.LOADING效果.
由于考虑到将类似内容视图之上显示加载框这种效果的状态定义为一个页面级状态不是一个好的做法，也与设计原则(页面级状态不能同时存在，widget小部件可以并存)不符合，那么将这种状态定义为一个widget级的小部件更为准确。这样的话通过这个状态实现更多其他的需求，扩展了使用场景，不仅仅是可以实现加载框了。
那么实现在CONTENT状态之上显示LOADING状态，可以这样做：
1.在该页面不再设置LOADING状态配置；
2.在该页面配置WIDGET_FLOAT状态信息；
3.在UiStatusController.bind()方法之后需要手动调用UiStatusController.showWidget()方法；
4.之后将通过UiStatusController.showWidget()和UiStatusController.hideWidget()方法来控制加载框的显示和隐藏.
