### ISSUE TITLE
如何动态更改widget里的文本

### ISSUE THREAD

**Issue by DancingDuck** [FengChenSunshine/UiStatus#5]
如,WIDGET_ELFIN 类型 提示推荐**条数据...这个一般都是动态的 emmm

**Comment by DancingDuck** [comment]
controller?.setOnLayoutStatusChangedListener(object :OnLayoutStatusChangedListener{
                            override fun onPrepareChanged(
                                target: Any,
                                view: View?,
                                uiStatus: Int,
                                isShow: Boolean
                            ) {
                                LogUtils.e(""+target+"_"+view+"_"+uiStatus)
                                if (uiStatus == ZStatus.WIDGET_ELFIN){
                                    view?.let {widget->
                                        var retry = widget.findViewById<TextView>(R.id.tv_hint_retry)
                                        retry.text = "成功为您推荐11条新内容"
                                    }
                                }
                            }

                            override fun onChangedComplete(
                                target: Any,
                                view: View,
                                uiStatus: Int,
                                isShow: Boolean
                            ) {
                                LogUtils.e(""+target+"_"+view+"_"+uiStatus)
                            }
                        })
这样处理了 不知道是不是好的法子

**Comment by DancingDuck** [comment]
这样处理会有问题,,,会先显示默认设置的文本

**Comment by FengChenSunshine** [comment]
你好，我测试了下在onPrepareChanged回调方法里修改显示内容没有出现先显示默认文本的情况的，你也则可以在你的if (uiStatus == ZStatus.WIDGET_ELFIN)判断修改为if (uiStatus == ZStatus.WIDGET_ELFIN&&isShow),因为这个回调表示状态准备改变，他在显示or隐藏时都会先回调该方法的

**Comment by FengChenSunshine** [comment]
在1.0.4版本以上增加了UiStatusController.getView(@UiStatus int uiStatus)和UiStatusController.getViewStrong(@UiStatus int uiStatus)方法，通过这两个方法可以获取对应状态的视图对象，进而可以获取到需要动态修改的View，这样就可以随时修改文本信息了.
详细信息可以查看Readme最后的版本更新说明.
