### ISSUE TITLE
能改变布局中文本的值吗？

### ISSUE THREAD

**Issue by longwQaQ** [FengChenSunshine/UiStatus#6]
不同页面的话术不同 要分别单独定义模版？

**Comment by FengChenSunshine** [comment]
你可以通过UiStatusController.setOnLayoutStatusChangedListener()方法来监听到视图状态的改变，OnLayoutStatusChangedListener接口中的onPrepareChanged回调和onChangedComplete回调中，都可以获取到当前正在显示的视图view，他们的第二个参数就是，从而可以操作这个view来改变想要显示的内容。eg:
uiStatusController.setOnLayoutStatusChangedListener(new OnLayoutStatusChangedListener(){
			public void onPrepareChanged(@NonNull Object target, @Nullable View view, @UiStatus int uiStatus, boolean isShow){
				((TextView)view).setText("在这里改变想要显示的内容");
			}
			public void onChangedComplete(@NonNull Object target, @Nullable View view, @UiStatus int uiStatus, boolean isShow){
				((TextView)view).setText("或者在这里也可以改变想要显示的内容");
			}
});

**Comment by FengChenSunshine** [comment]
在1.0.4版本以上增加了UiStatusController.getView(@UiStatus int uiStatus)和UiStatusController.getViewStrong(@UiStatus int uiStatus)方法，通过这两个方法可以获取对应状态的视图对象，进而可以获取到需要动态修改的View，这样就可以随时修改文本信息了.
详细信息可以查看Readme最后的版本更新说明.
