### ISSUE TITLE
view显示不正常

### ISSUE THREAD

**Issue by Huping95** [FengChenSunshine/UiStatus#7]
你好，demo中的 ‘在View中使用’  ，如果设置一个marginTop值，真机上跑起来，就变形了（View高度写死的），感觉是像在内部设置了一个padding值，或者是将原View包裹了一个布局，设置了一个margin值

**Comment by FengChenSunshine** [comment]
你好，根据你的描述测了下没有发现有什么问题。方便的话可以贴出代码看下吗？或者加我微信DL781613203交流。

**Comment by FengChenSunshine** [comment]
在1.0.4版本以上已经修复了这个问题.
详细信息可以查看Readme最后的版本更新说明.
