### ISSUE TITLE
一个视图里怎么设置多个点击事件？

### ISSUE THREAD

**Issue by longwQaQ** [FengChenSunshine/UiStatus#8]
一个视图里怎么设置多个点击事件？

**Comment by FengChenSunshine** [comment]
你好，一般情况下点击事件只有一个，如果需要设置多个的话可以通过UiStatusController.setOnLayoutStatusChangedListener(OnLayoutStatusChangedListener listener);方法实现。
比如可以在OnLayoutStatusChangedListener监听器的void onChangedComplete(@NonNull Object target, @NonNull View view, @UiStatus int uiStatus, boolean isShow);回调里处理。
其中第4个参数为true时表示当前正在显示该视图，第二个参数view是视图的View对象，可以使用该view对象通过findViewById找到需要的控件来设置点击事件。

**Comment by longwQaQ** [comment]
好的  我试试 谢谢
