### ISSUE TITLE
点击事件监听为什么会把页面状态重置到加载？

### ISSUE THREAD

**Issue by longwQaQ** [FengChenSunshine/UiStatus#9]
我点击某个按钮  只想弹出一个弹窗  页面保持不变  但是这样页面就会回到LOADING 状态
![image](https://user-images.githubusercontent.com/41498415/72070309-33da3880-3324-11ea-8a89-2ea5009983b9.png)

**Comment by FengChenSunshine** [comment]
你好，考虑到重试按钮点击后大部分情况为重新加载，所以默认重试时展示loading视图，但是在UiStatusController对象里提供了方法可以关闭这个默认操作：
UiStatusController.setAutoLoadingWithRetry(boolean isAutoLoadingWithRetry);
参数isAutoLoadingWithRetry ：重试时是否自动切换到加载中视图:true自动切换,false不切换.

**Comment by longwQaQ** [comment]
请问一个视图里怎么设置多个点击事件？ 比如里面有2个按钮  一个是重新加载  一个是回到首页 类似这种  如何设置点击事件？

**Comment by FengChenSunshine** [comment]
[多个点击事件参考这里](https://github.com/FengChenSunshine/UiStatus/issues/8)
